### ISSUE TITLE
ImagickException: The width and height must be greater than zero  

### ISSUE THREAD

**Issue by Kaitain-113** [jansenfelipe/omr#27]
This error occurs when mapping large images.

**Comment by ArianNexux** [comment]
Did you find a solution?
I'm getting the same error!

**Comment by ArianNexux** [comment]
I solved this problem compressing the image, I used a service to do it and after that i send the image processed to the script omr.

**Comment by Kaitain-113** [comment]
@ArianNexux I found the source of the error

the problem is the resolution of the checkbox

positions x2 and y2 cannot be less than or equal to positions x1 and y1

This error is caused by a code snippet that I don't quite understand how it works.

**File: ImagickScanner.php**
**Lines: 213 and 214**

Right, work fine:

```
targets": [
      {
        "x1": 50,
        "y1": 10,
        "x2": 51,
        "y2": 11,
        "id": "Satisfação: Ruim",
        "type": "rectangle",
        "tolerance": 10
      }
    ]

```

Error:

```
targets": [
      {
        "x1": 50,
        "y1": 10,
        "x2": 50,
        "y2": 10,
        "id": "Satisfação: Ruim",
        "type": "rectangle",
        "tolerance": 10
      }
    ]

```

**Comment by ArianNexux** [comment]
Thank you @kaetaen

**Comment by ArianNexux** [comment]
@kaetaen Could you send me your Discord?
